services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    restart: unless-stopped
    ports:
      - "1935:1935"        # RTMP (OBS)
      - "8189:8189/udp"    # WebRTC media - NUEVO
    expose:
      - "8888"             # HLS -> stream.sosparatuvida.com.co
      - "8889"             # WHIP -> publish.sosparatuvida.com.co - NUEVO
      - "9997"             # API de control (NUEVO) - solo interno, nunca en "ports"
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
      - ./recordings:/recordings   # NUEVO - persiste grabaciones fuera del contenedor
    networks:
      - dokploy-network


networks:
  dokploy-network:
    external: true