services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    restart: unless-stopped
    ports:
      - "1935:1935"        # RTMP (OBS)
      - "8189:8189/udp"    # WebRTC media - NUEVO
    expose:
      - "8888"             # HLS -> stream.sosparatuvida.com.co
      - "8889"             # WHIP -> publish.sosparatuvida.com.co - NUEVO
    volumes:
      - ./mediamtx.yml:/mediamtx.yml

networks:
  dokploy-network:
    external: true